{{- $secretname := printf "%s-auth" .Values.service.name -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
{{- if empty $secret -}}
  username: {{ default .Values.auth.username "admin" | b64enc | quote }}
  password: {{ default .Values.auth.password (randAlphaNum 32) | b64enc | quote }}
{{else}}
  username: {{ (lookup "v1" "Secret" .Release.Namespace $secretname).data.username }}
  password: {{ (lookup "v1" "Secret" .Release.Namespace $secretname).data.password }}
{{end -}}