apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  username: {{ .Values.auth.username | default "admin" | b64enc | quote }}
  password: {{ .Values.auth.password | default (randAlphaNum 32) | b64enc | quote }}