apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
  - "{{ .Values.service.name }}.{{ .Values.istio.domain }}""
  gateways:
  - {{ .Values.istio.gateway }}
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}
        port:
          number: {{ .Values.service.externalPort }}
